### ISSUE TITLE
Finalize content: /speakers-guide

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#117]
- [x] create page `/speakers-guide` (added in #120)
- [x] take content from here: https://2017.cssconf.eu/speakers-guide/ (#117)
- [x] update content for 2018 (#117)
- [x] add content: technical details
- [x] add content: schedule and social events
- [ ] add photos & contact data of team
- [x] add content" code of conduct
- [x] add content: childcare and accessibility 
- [ ] share with all speakers (@Lucie-H ?)

**Comment by Kriesse** [comment]
@jan Would you like to have the same on jsconf.eu?

**Comment by jan** [comment]
@Kriesse Who summoned me?

**Comment by Kriesse** [comment]
@jan Argh, github nickname confusion, this was intended for janl. Apologies!

**Comment by janl** [comment]
yelps <3

**Comment by Kriesse** [comment]
@janl https://github.com/jsconf/2018.jsconf.eu/issues/148
